### ISSUE TITLE
Proposal: no password on the screen (mostly for CLI)

### ISSUE THREAD

**Issue by stesix** [Cretezy/MasterPassX#10]
mpx should not show the calculated password on the screen but it should set it directly in the clipboard (and maybe enforce a timeout as well after which the password gets obliterated).

**Comment by Cretezy** [comment]
This is a good idea. Using something like https://github.com/xavi-/node-copy-paste would seem useful.

Maybe ask the user during the setup process if they wish to have the passwords copied or showed by default, and have a flag to set either one of them.

What do you think about that?

**Comment by stesix** [comment]
IMO it sounds good. For what concerns the node-copy-paste, I read the code and it's using callbacks that I personally hate. I propose to use clipboardy (https://github.com/sindresorhus/clipboardy).

**Comment by Cretezy** [comment]
Good idea, although I'd like to introduce you to [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original) [(example)](http://2ality.com/2017/05/util-promisify.html) :)

Whichever copying module we use is really just a detail and can always be swapped later.

Do you want to implement this feature? I would be here to guide you through if you have any questions!

**Comment by stesix** [comment]
kewl... I was not aware of promisify. Thx. Yes, I'll take care of the copy option.

**Comment by Cretezy** [comment]
Perfect! You can ask questions on this thread or if anything you can find my email on my GitHub profile.

**Comment by stesix** [comment]
it's about 6 hours that I'm trying to add new modules and to use them. The code seems correct but I can't test. Everytime something goes nuts in the building process. I always thought that it was enough to use `yarn add clipboardy` or `yarn add copy-paste` (or via npm using `npm install -g clipboardy`) and simply execute `yarn build`. Even following the next small script (which takes about 15 minutes to execute so it's extremely unpleasant) doesn't work.

```
#!/bin/bash

cd MasterPassX
find . -name node_modules -exec rm -rf {} \; 2>/dev/null
find . -name "*.lock" -delete
yarn cache clean
yarn --force
pushd core && yarn build && popd
cd cli && yarn build
node dist/index.js -tx testing
```

Please explain what's the trick to add new modules in the code. It doesn't matter what OS I use, I end up always with the same errors.

**Comment by Cretezy** [comment]
Make sure you have an up-to-datw version of yarn. Run the yarn command in the cli dir.
Since we use yarn workspaces, the dependencies are installed in the root node_module, but it is linked by yarn automatically.

**Comment by stesix** [comment]
Already checked yarn. It's the latest version (1.3.2). Can you please try to add and use a copy&paste module and tell me if everything works as expected? When I add clipboardy I get some missing dependencies (and it won't work) when I use copy-paste, it throws a `[!] Error: Could not resolve './platform/openbsd' from ../node_modules/copy-paste/index.js` (which is actually true... it does not exist)

**Comment by Cretezy** [comment]
Have you gotten this to work?

**Comment by Cretezy** [comment]
I think this should also be added to the web version, simple as a toggle under "Users" in the nav bar as "show passwords". Should be simple enough to implement.

**Comment by Cretezy** [comment]
Well this is way too late but I've started working on this again and I've added it in. It's available in https://github.com/cretezy/masterpassx/tree/rewrite (will be pushed in the coming days/weeks)
