### ISSUE TITLE
cli: `-c` `--counter`

### ISSUE THREAD

**Issue by evandrix** [Cretezy/MasterPassX#18]
https://github.com/Cretezy/MasterPassX/blob/master/cli/src/index.js#L22

suffers from issue

https://github.com/tj/commander.js/issues/523

**Comment by Cretezy** [comment]
Can confirm bug is there. I'm working on a newer version (see `rewrite`) branch, will try to fix there. Thanks for the report!

**Comment by evandrix** [comment]
np, the fix is just to simply replace `parseInt` with something like `x=>parseInt(x)`

i'll close the issue now
