### ISSUE TITLE
cli - `counter` option `parseInt` incorrect

### ISSUE THREAD

**Issue by evandrix** [Cretezy/MasterPassX#20]
i.e. https://github.com/Cretezy/MasterPassX/blob/master/cli/src/index.js#L22
due to changes in https://github.com/tj/commander.js#custom-option-processing,
it should now be `(v,prev)=>parseInt(v)`

**Comment by Cretezy** [comment]
Related to https://github.com/Cretezy/MasterPassX/issues/18

**Comment by Cretezy** [comment]
Just letting you know, I'm slowly rebuilding most of the project in TypeScript. I don't actively use it so my time is limited!
