### ISSUE TITLE
Better master password input

### ISSUE THREAD

**Issue by Cretezy** [Cretezy/MasterPassX#3]
The master password is the easier piece to break. We should show the user recommendation about the master password they choose like:

- Length (most important)
- If it is a common password (use third-party password list and download only when typing a master password)

**Comment by Cretezy** [comment]
Also have a form of output to check if it is the correct password. Maybe something like a word of the dictionary? Emojis might be a great fit for this (display 2 emojis based on password). This should be secure enough that knowning this output can't reverse to to the password and it should also be unique enough.

**Comment by FedericoYundt** [comment]
You can implement [zxcvbn](https://github.com/dropbox/zxcvbn) library. This is what easypasswords do https://github.com/palant/easypasswords/issues/62

**Comment by Cretezy** [comment]
@FedericoYundt Thank you for the library reminded. I've started work on implementing it, I'll link the commit once I have completed the addition.

**Comment by Cretezy** [comment]
Implemented at https://github.com/Cretezy/MasterPassX/commit/fb19a9b4e96b47dbb371e81ca66de412bb558761#diff-9c18127129910036ce89e695cbfbf1bf

Thank you for the suggestion!

I've made it load zxcvbn asynchronously to avoid loading it on each load since it's a large library (~500kb). It only loads when the add user form is shown.
