### ISSUE TITLE
Improve documentation 

### ISSUE THREAD

**Issue by stesix** [Cretezy/MasterPassX#6]
Specifically it's not an easy task to start contributing to the project since the testing is hard.

An "how to build a working version of mpx from the repo" would be an awesome starting point.

**Comment by Cretezy** [comment]
https://github.com/Cretezy/MasterPassX/commit/d80ffa4b0f246d42ce93947cc0f704c8270010ee

https://github.com/Cretezy/MasterPassX/blob/master/CONTRIBUTING.md

Let me know what else to add. I quickly drafted up a CONTRIBUTING.

**Comment by stesix** [comment]
I'm mostly interested in expanding the cli and currently it's not very clear to me how to include the core libs in a nice way. I haven't thought about fixing the topic on my own since I don't have a proper nice solution in mind and I'm not very familiar with your approach yet.
